### PR TITLE
Some minor configuration changes

### PR DESCRIPTION
**Pull request by sourlemon11**
Following your installation instructions, you need to set the PATH to the autojump bin in home. Completions weren't working for me until I renamed the file to match the command (same as in fish [completions](https://github.com/fish-shell/fish-shell/tree/master/share/completions)).

### CODE REVIEW

**Comment by jethrokuan** [comment]
I don't maintain this anymore, since I find `z` to serve the same functionality, with no python deps. I'll merge this, let me know if you're willing to take over the maintenance of this repo.

**Comment by sourlemon11** [comment]
I was actually trying out z on fisherman, but I ran into a strange bug. Using this plugin was a bit easier than trying to find the source of that error.

**Comment by jethrokuan** [comment]
Do let me know what you're facing, I can help you fix that

**Comment by sourlemon11** [comment]
Ok. Submitted an issue. I can't stay on for much longer. So I'll comment tomorrow.

**Pull request merged**
